Figaro.require_keys(
  'MAILER_SENDER',
  'MAILER_HOST',
  'SMTP_ADDRESS',
  'SMTP_USERNAME',
  'SMTP_DOMAIN',
  'SMTP_PASSWORD'
  # 'AWS_S3_BUCKET',
  # 'AWS_S3_BUCKET_FOLDER',
  # 'AWS_ACCESS_KEY_ID',
  # 'AWS_SECRET_ACCESS_KEY',
  # 'AWS_REGION',
  # # 'AWS_S3_ENDPOINT'
)
